services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
      - ../secrets/certificate/cert.pem:/etc/ssl/certs/inception.crt:ro
      - ../secrets/certificate/key.pem:/etc/ssl/private/inception.key:ro
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    environment:
      - WP_WEBSITE_URL=https://${DOMAIN_NAME}
      - WP_DB=${WP_DB}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/www/html/wp-config.php && pidof php-fpm83 >/dev/null 2>&1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: on-failure
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=${WP_DB}
      - MARIADB_USER=${WP_DB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root --password=\"$(cat /run/secrets/db_root_password)\""]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mysql
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
